#application.name: Gateway-Service
server.port: 8083

eureka:
  instance:
    client:
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
  client:
    register-with-eureka: true
    fetch-registry: true

spring:
  application:
    name: Gateway-Service
  cloud:
    gateway:
      routes:
        - id: STUDENT-SERVICE
          uri: http://localhost:8081
#          uri: lb://STUDENT-SERVICE # Use service name for load balancing
          predicates:
            - Path=/student/**
        - id: HOSTEL-SERVICE
          uri: http://localhost:8082 # Use service name for load balancing
#          uri: lb://HOSTEL-SERVICE
          predicates:
            - Path=/hostel/**